using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.UI.Shipyard
{
    [GenerateTypedNameReferences]
    public sealed partial class ShipLabelerWindow : DefaultWindow
    {

        public event Action<string>? OnRename;

        private bool _focused;

        private string _name = string.Empty;

        public ShipLabelerWindow()
        {
            RobustXamlLoader.Load(this);

            SubmitRenameButton.Disabled = true;
            SubmitRenameButton.OnPressed += _ =>
            {
                OnRename?.Invoke(_name);
            };

            NameEdit.OnTextChanged += e =>
            {
                _name = e.Text;
                SubmitRenameButton.Disabled = false;
                StatusLabel.Visible = false;
            };

            NameEdit.OnFocusEnter += _ => _focused = true;
            NameEdit.OnFocusExit += _ =>
            {
                _focused = false;
                NameEdit.Text = _name;
            };
        }

        public void SetCurrentName(string name)
        {
            if (name == _name)
                return;

            _name = name;
            if (!_focused)
                NameEdit.Text = name;
        }

        public void SetNameMaxLength(int maxLength)
        {
            NameEdit.IsValid = s => s.Length <= maxLength;
        }

        public void SetStatus(string status) {
            StatusLabel.Visible = true;
            StatusLabel.Text = status;
        }
    }
}
