using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI.ProfileEditorControls.Appearance;

[GenerateTypedNameReferences]
public sealed partial class AgeEditor : BoxContainer
{
    private ProfileEditor? _editor;
    public event Action? OnUpdate;

    public AgeEditor()
    {
        RobustXamlLoader.Load(this);
        AgeEdit.OnTextChanged += HandleTextChanged;
    }

    public void Initialize(ProfileEditor editor)
    {
        _editor = editor;
        if (_editor.Profile is not HumanoidCharacterProfile)
        {
            Visible = false;
            return;
        }

        Visible = true;
        Refresh();
    }

    public void Refresh()
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;

        AgeEdit.Text = humanoid.Age.ToString();
    }

    private void HandleTextChanged(LineEdit.LineEditEventArgs evt)
    {
        if (!int.TryParse(evt.Text, out var newAge))
            return;

        SetAge(newAge);
    }

    private void SetAge(int newAge)
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;

        _editor.Profile = humanoid.WithAge(newAge);
        OnUpdate?.Invoke();
    }
}
