using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI.ProfileEditorControls.Appearance;

[GenerateTypedNameReferences]
public sealed partial class EyeColorEditor : BoxContainer
{
    private ProfileEditor? _editor;
    public event Action? OnUpdate;
    public event Action<Color>? OnUpdateColor;

    public EyeColorEditor()
    {
        RobustXamlLoader.Load(this);
        EyeColorPicker.OnEyeColorPicked += HandleColorChanged;
    }

    public void Initialize(ProfileEditor profileEditor)
    {
        _editor = profileEditor;
        if (_editor.Profile is not HumanoidCharacterProfile)
        {
            Visible = false;
            return;
        }

        Visible = true;
        Refresh();
    }

    public void Refresh()
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;

        EyeColorPicker.SetData(humanoid.Appearance.EyeColor);
    }

    private void HandleColorChanged(Color newColor)
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;
        _editor.Profile = humanoid.WithCharacterAppearance(humanoid.Appearance.WithEyeColor(newColor));
        OnUpdateColor?.Invoke(newColor);
        OnUpdate?.Invoke();
    }
}
