using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI.ProfileEditorControls.Appearance;

[GenerateTypedNameReferences]
public sealed partial class SexEditor : BoxContainer
{

    private ProfileEditor? _editor;
    private IPrototypeManager _prototypeManager = default!;
    public event Action? OnUpdate;
    public event Action<Sex>? OnUpdateSex;

    public SexEditor()
    {
        RobustXamlLoader.Load(this);
        SexButton.OnItemSelected += HandleSelected;
    }

    public void Initialize(ProfileEditor profileEditor, IPrototypeManager protoMan)
    {
        _editor = profileEditor;
        _prototypeManager = protoMan;
        if (_editor.Profile is not HumanoidCharacterProfile)
        {
            Visible = false;
            return;
        }

        Visible = true;
        Refresh();
    }

    private void HandleSelected(OptionButton.ItemSelectedEventArgs e)
    {
        SexButton.SelectId(e.Id);
        SetSex((Sex)e.Id);
    }

    private void SetSex(Sex newSex)
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;

        _editor.Profile = humanoid.WithSex(newSex);
        // for convenience, default to most common gender when new sex is selected

        OnUpdateSex?.Invoke(newSex);
        OnUpdate?.Invoke();
    }

    public void Refresh()
    {
        if (_editor?.Profile is not HumanoidCharacterProfile humanoid)
            return;

        var sexes = new List<Sex>();

        // add species sex options, default to just none if we are in bizzaro world and have no species
        if (_prototypeManager.TryIndex(humanoid.Species, out var speciesProto))
        {
            sexes.AddRange(speciesProto.Sexes);
        }
        else
        {
            sexes.Add(Sex.Unsexed);
        }

        SexButton.Clear();

        // add button for each sex
        foreach (var sex in sexes)
        {
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
        }

        if (sexes.Contains(humanoid.Sex))
        {
            SexButton.SelectId((int)humanoid.Sex);
        }
        else
        {
            SexButton.SelectId((int)sexes[0]);
        }

    }
}
