using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI.ProfileEditorControls.Appearance;

[GenerateTypedNameReferences]
public sealed partial class ShowClothesEditor : BoxContainer
{
    private ProfileEditor? _editor;
    public event Action? OnUpdate;

    public bool Pressed => ShowClothes.Pressed;

    public ShowClothesEditor()
    {
        RobustXamlLoader.Load(this);
        ShowClothes.OnToggled += HandleOnPressed;
    }

    public void Initialize(ProfileEditor editor)
    {
        _editor = editor;
        if (_editor.Profile is not HumanoidCharacterProfile)
        {
            Visible = false;
            return;
        }
        Visible = true;
    }

    private void HandleOnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnUpdate?.Invoke();
    }
}
