using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI.ProfileEditorControls;

[GenerateTypedNameReferences]
public sealed partial class AppearanceTab : BoxContainer
{
    public bool ShowClothes => ShowClothesEditor.Pressed;

    private bool _eventsInitialized;

    public AppearanceTab()
    {
        RobustXamlLoader.Load(this);
    }

    public void Initialize(ProfileEditor editor, IPrototypeManager protoMan, MarkingManager markMan)
    {
        SpeciesEditor.Initialize(editor, protoMan);
        AgeEditor.Initialize(editor);
        SexEditor.Initialize(editor, protoMan);
        PronounsEditor.Initialize(editor);
        ShowClothesEditor.Initialize(editor);
        SpawnPriorityEditor.Initialize(editor);
        SkinEditor.Initialize(editor, protoMan);
        HairEditor.Initialize(editor, markMan, protoMan);
        EyeColorEditor.Initialize(editor);

        if (!_eventsInitialized)
            InitializeEvents(editor);
    }

    private void InitializeEvents(ProfileEditor editor)
    {
        SpeciesEditor.OnUpdate += SkinEditor.Refresh;
        SpeciesEditor.OnUpdateSpecies += editor.Markings.SetSpecies;
        SpeciesEditor.OnUpdate += editor.Jobs.RefreshJobs;
        SpeciesEditor.OnUpdate += editor.Antags.RefreshAntags;
        SpeciesEditor.OnUpdate += editor.Jobs.RefreshLoadouts;
        SpeciesEditor.OnUpdate += SexEditor.Refresh;
        SpeciesEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;
        SpeciesEditor.OnUpdate += HairEditor.Refresh;

        AgeEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;
        AgeEditor.OnUpdate += editor.SetDirty;

        SexEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;
        SexEditor.OnUpdateSex += PronounsEditor.SetFromSex;
        SexEditor.OnUpdateSex += editor.Markings.SetSex;
        SexEditor.OnUpdate += editor.SetDirty;

        PronounsEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;
        PronounsEditor.OnUpdate += editor.SetDirty;

        ShowClothesEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;

        SpawnPriorityEditor.OnUpdate += editor.SetDirty;

        SkinEditor.OnUpdateSkinColor += editor.Markings.SetSkinColor;
        SkinEditor.OnUpdate += editor.PreviewPanel.ReloadProfilePreview;
        SkinEditor.OnUpdate += editor.SetDirty;

        HairEditor.OnUpdate += editor.PreviewPanel.ReloadPreview;
        HairEditor.OnUpdate += editor.SetDirty;
        HairEditor.OnChangeCMarkingsHair += editor.Markings.SetHairMarking;
        HairEditor.OnChangeCMarkingsFacialHair += editor.Markings.SetFacialHairMarking;

        EyeColorEditor.OnUpdate += editor.PreviewPanel.ReloadProfilePreview;
        EyeColorEditor.OnUpdate += editor.SetDirty;
        EyeColorEditor.OnUpdateColor += editor.Markings.SetEyeColor;

        _eventsInitialized = true;
    }

    public void RefreshSpecies()
    {
        SpeciesEditor.Refresh();
    }
}
