using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        private IClientPreferencesManager _preferencesManager = default!;
        private ISharedPlayerManager _playerManager = default!;
        private IEntityManager _entManager = default!;
        private IPrototypeManager _protomanager = default!;

        private readonly Button _createNewCharacterButton;
        private readonly Button _createNewBorgButton;
        private readonly ProfileEditor _profileEditor;
        public int? SelectedCharacterSlot;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;
        public event Action<(int, bool)>? SetCharacterEnable;

        public CharacterSetupGui(
            IClientPreferencesManager prefMan,
            ISharedPlayerManager playerMan,
            IEntityManager entMan,
            IPrototypeManager protoMan,
            IResourceCache resMan,
            IConfigurationManager confMan,
            ProfileEditor profileEditor,
            JobPriorityEditor jobPriorityEditor)
        {
            _preferencesManager = prefMan;
            _playerManager = playerMan;
            _entManager = entMan;
            _protomanager = protoMan;
            _profileEditor = profileEditor;
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var panelTex = resMan.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            _createNewBorgButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-borg-button"),
            };

            _createNewBorgButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(BorgCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            JobPriorityEditor.AddChild(jobPriorityEditor);
            RulesButton.OnPressed += _ => new RulesAndInfoWindow().Open();

            StatsButton.OnPressed += _ => new PlaytimeStatsWindow().OpenCentered();

            confMan.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);

            JobPrioritiesButton.OnPressed += args =>
            {
                jobPriorityEditor.LoadJobPriorities();
                CharEditor.Visible = false;
                JobPriorityEditor.Visible = true;
            };
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            _createNewBorgButton.Orphan();
            Characters.DisposeAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            // Include the Edit Job Priorities button into this group
            JobPrioritiesButton.Group = characterButtonsGroup;

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            CharEditor.Visible = true;
            JobPriorityEditor.Visible = false;

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            // If there is no slot selected and no profile loaded, we will select the first one
            var first = !SelectedCharacterSlot.HasValue;
            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                var isSelected = SelectedCharacterSlot.HasValue ? slot == SelectedCharacterSlot : first;
                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(
                    _preferencesManager,
                    _protomanager,
                    _entManager,
                    _playerManager,
                    characterButtonsGroup,
                    character,
                    isSelected);

                // If this button is selected we need to initialize the editor with this profile
                if (isSelected && _profileEditor.Profile == null)
                    _profileEditor.SetProfile(slot);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectedCharacterSlot = slot;
                    SelectCharacter?.Invoke(slot);
                    CharEditor.Visible = true;
                    JobPriorityEditor.Visible = false;
                    _profileEditor.SetProfile(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };

                characterPickerButton.OnEnableToggled += pressed =>
                {
                    SetCharacterEnable?.Invoke((slot, pressed));
                };
                if(first)
                    first = false;
            }

            _createNewBorgButton.Disabled = _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
            Characters.AddChild(_createNewBorgButton);
        }
    }
}
