name: Check PR Target Branch

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR destination
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          echo "PR is targeting branch: $TARGET_BRANCH"
          
          if [ "$TARGET_BRANCH" != "starlight-dev" ]; then
            echo "Error: PR must target 'starlight-dev' branch, but targets '$TARGET_BRANCH'"
            echo "Please change the target branch to 'starlight-dev'"
            exit 1
          else
            echo "Success: PR correctly targets 'starlight-dev' branch"
          fi
